services:
  redis:
    container_name: redis
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    environment:
      DEBUG: true
      REDIS_PASSWORD: redis_password
    command: ["redis-server"]

  postgres:
    container_name: postgres
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      # POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=en-US --lc-collate=POSIX.UTF-8"
      # LC_COLLATE: C.UTF-8
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_db
      POSTGRES_PASSWORD: postgres_password
      # POSTGRES_HOST_AUTH_METHOD: trust

  # https://redis.io/docs/latest/operate/redisinsight/install/install-on-docker/
  redis_insight:
    container_name: redis_insight
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - 5540:5540
