services:
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    environment:
      DEBUG: true
      REDIS_PASSWORD: redis_password
    command: ["redis-server"]

  postgres:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_db
      POSTGRES_PASSWORD: postgres_password
      # POSTGRES_HOST_AUTH_METHOD: trust
